build:
  maxIssues: 0
  excludeCorrectable: false
  weights:

console-reports:
  active: true

output-reports:
  active: true

comments:
  active: true
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

complexity:
  active: true
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7
  ComplexMethod:
    active: true
    threshold: 15
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20

coroutines:
  active: true

empty-blocks:
  active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false
  TooGenericExceptionThrown:
    active: false

formatting:
  active: true
  android: false
  autoCorrect: true

naming:
  active: true
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  VariableNaming:
    active: true
    variablePattern: '[a-z][a-zA-Z0-9]*'

performance:
  active: true

potential-bugs:
  active: true

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
  ForbiddenComment:
    active: false
  MagicNumber:
    active: false
  UnusedPrivateMember:
    active: true
